name: CodeCov

on:
  push:
    branches: [master]
  workflow_run:
    workflows: ['Receive PR']
    types:
      - completed

jobs:
  CodeCov:
    environment: ali_oss_AK
    runs-on: ubuntu-latest
    env:
      ALI_SDK_OSS_ID: ${{secrets.ALI_SDK_OSS_ID}}
      ALI_SDK_OSS_SECRET: ${{secrets.ALI_SDK_OSS_SECRET}}
      ALI_SDK_STS_BUCKET: ${{secrets.ALI_SDK_STS_BUCKET}}
      ALI_SDK_STS_ID: ${{secrets.ALI_SDK_STS_ID}}
      ALI_SDK_STS_REGION: ${{secrets.ALI_SDK_STS_REGION}}
      ALI_SDK_STS_ROLE: ${{secrets.ALI_SDK_STS_ROLE}}
      ALI_SDK_STS_SECRET: ${{secrets.ALI_SDK_STS_SECRET}}
    steps:
    - uses: actions/checkout@v2
    - name: test and report upload
      run: |
        npm install
        npm run test-cov
        npx codecov -t ${{secrets.CODECOV_KEY}} # not required for public repos
