name: CodeCov
on: 
  push: 
    branches: [ master ]
  workflow_run:
    workflows: ["Receive PR"]
    types:
      - completed

jobs:
  CodeCov:
    environment: ali_oss_AK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_KEY}} # not required for public repos
          name: codecov-umbrella # optional
          files: ./coverage
