name: CodeCov

on:
  push:
    branches: [master]
  workflow_run:
    workflows: ['Receive PR']
    types:
      - completed

jobs:
  CodeCov:
    environment: ali_oss_AK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test and report upload
      run: |
        npm install
        npm run test-cov
        npx codecov -t ${{secrets.CODECOV_KEY}} # not required for public repos
