name: SNYK_SCAN
on: 
  push: 
    branches: [ 7.x ]
  workflow_run:
    workflows: ["Receive PR"]
    types:
      - completed

jobs:
  security:
    environment: ali_oss_AK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkoutV2
        with:
          ref: 7.x
      - run: npm install
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_KEY }}
