name: SNYK_SCAN
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  security:
    environment: ali_oss_AK
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.ALI_SDK_OSS_ID }} = ${{ secrets.ALI_SDK_STS_BUCKET }}"
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: npm install
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_KEY }}
